version: '3'
services:
  maxkey-mysql:
    image: maxkey:mysql
    container_name: maxkey-mysql
    build: ./docker-mysql
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/logs:/var/log/mysql
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=maxkey
    ports:
      - "3316:3306"
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    
  maxkey:
    image: maxkey:maxkey
    container_name: maxkey
    build: ./docker-maxkey
    environment:
      - DATABASE_HOST:maxkey-mysql
      - DATABASE_PORT:3306
      - DATABASE_NAME:maxkey
      - DATABASE_USER:root
      - DATABASE_PWD:maxkey
    ports:
      - "8092:443"

  maxkey-mgt:
    image: maxkey:maxkey-mgt
    container_name: maxkey-mgt
    build: ./docker-maxkey-mgt
    environment:
      - DATABASE_HOST:maxkey-mysql
      - DATABASE_PORT:3306
      - DATABASE_NAME:maxkey
      - DATABASE_USER:root
      - DATABASE_PWD:maxkey
    ports:
      - "8093:9527"
